steps:
- name: 'gcr.io/cloud-builders/node'
  entrypoint: bash
  args:
    - '-c'
    - |
       if [[ -d ./server ]];
       then
            npm install ./server
       fi
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  dir: './server'

timeout: "1600s"
