steps:
- name: node
  entrypoint: bash
  args:
    - '-c'
    - |
       if [[ -d ./server ]] && [[ -d ./frontend ]];
       then
            npm install ./server
            npm install ./frontend
       else
            npm install ./server
       fi
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  dir: './server'

timeout: "1600s"
