steps:
- name: 'node12'
  entrypoint: npm
  args:
    - "bash"
    - "-c"
    - |
        if [[ -d ./server ]] && [[ -d ./frontend ]];
        then
              npm install ./server && \
              npm install ./frontend && \
              gcloud app deploy ./frontend/app.yaml && \
              gcloud app deploy ./server/app.yaml
        else
              npm install ./server && \
              gcloud app deploy ./server/app.yaml
        fi

timeout: "1600s"
