runtime: nodejs12

instance_class: F4

service: shule-backend

env_variables:
  DB_HOST: 10.38.64.2
  DB_USER: developer
  DB_PASS: shule34HEdfer
  DB_NAME: shule_db
  DB_PORT: 3306
  DB_CONNECTION_NAME: gads-app-demo:us-central1:demo-db-10
 
handlers:
- url: /.*
  secure: always
  script: auto

beta_settings:
  cloud_sql_instances: gads-app-demo:us-central1:demo-db-10:shule_db:3306

vpc_access_connector:
  name: projects/gads-app-demo/locations/us-central1/connectors/app-to-cloud-sql

automatic_scaling:
  target_cpu_utilization: 0.80
  min_instances: 1
  max_instances: 5
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

