runtime: nodejs12

instance_class: B1


env_variables:
  DB_HOST: 10.114.208.2
  DB_USER: admin
  DB_PASS: shule-1234-adminOPE345
  DB_NAME: shule_db
  DB_PORT: 3306
  DB_CONNECTION_NAME: gads-app-demo:us-central1:shule-db

beta_settings:
  cloud_sql_instances: gads-app-demo:shule-db:shule_db:3306

vpc_access_connector:
  name: projects/gads-app-demo/locations/us-central1/connectors/shule-app-connector

basic_scaling:
  max_instances: 3
  idle_timeout: 10m

