runtime: nodejs12

instance_class: B4

service: shule-backend

env_variables:
  DB_HOST: 10.38.64.2
  DB_USER: developer
  DB_PASS: shule34HEdfer
  DB_NAME: shule_db
  DB_PORT: 3306
  DB_CONNECTION_NAME: gads-app-demo:us-central1:demo-db-10
 
handlers:
- url: /.*
  secure: always
  script: auto

beta_settings:
  cloud_sql_instances: gads-app-demo:us-central1:demo-db-10:shule_db:3306

vpc_access_connector:
  name: projects/gads-app-demo/locations/us-central1/connectors/app-to-cloud-sql

basic_scaling:  
  max_instances: 2
  idle_timeout: 10m


