runtime: nodejs12

instance_class: F4

env_variables:
  DB_HOST: 10.103.32.5
  DB_USER: developer
  DB_PASS: shule34HEdfer
  DB_NAME: shule_db
  DB_PORT: 3306
  DB_CONNECTION_NAME: team-mysql-db:us-central1:shule-db-vs-8
 
handlers:
- url: /.*
  secure: always
  script: auto

beta_settings:
  cloud_sql_instances: team-mysql-db:shule-db-vs-8:shule_db:3306

vpc_access_connector:
  name: projects/team-mysql-db/locations/us-central1/connectors/the-vpc-connector

automatic_scaling:
  target_cpu_utilization: 0.80
  min_instances: 1
  max_instances: 5
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

